version: "1.0"
services:
  client:
    ports:
      - "3001:3001"
    image: dams38/infrescoinmarketcap_client
    links: api
  api:
    image: dams38/infrescoinmarketcap_api
    ports:
      - "3000:3000"