name: workflow-main
on:
  push:
    branches:
    - main
    - feature/*
jobs:
  publish-api:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Hub log in
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build api/. -t ${{ secrets.DOCKER_USERNAME }}/infrescoinmarketcap_api
      - run: docker push ${{ secrets.DOCKER_USERNAME  }}/infrescoinmarketcap_api
  publish-client:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Hub log in
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build api/. -t ${{ secrets.DOCKER_USERNAME }}/infrescoinmarketcap_client
      - run: docker push ${{ secrets.DOCKER_USERNAME  }}/infrescoinmarketcap_client